### PR TITLE
纸上得来终觉浅,绝知此事要PR

### PR DESCRIPTION
**Pull request by tomatopunk**
修复TIKV源码解析中的拼写错误. (TiKV 源码解析系列文章（十一）Storage - 事务控制层)

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
LGTM

**Comment by tisonkun** [comment]
@yikeke @TomShawn PTAL. I'm unsure whether we should pick to other branch or there is related settings to be changed.

**Review by YUXI903 — APPROVED** [review]
LGTM @YiniXu9506

**Comment by tomatopunk** [comment]
> @yikeke @TomShawn PTAL. I'm unsure whether we should pick to other branch or there is related settings to be changed.

In addition, due to the changes in tikv#9508, most of the code locations in the tikv source code parsing series have been changed 🧐

**Comment by tisonkun** [comment]
> > @yikeke @TomShawn PTAL. I'm unsure whether we should pick to other branch or there is related settings to be changed.
> 
> In addition, due to the changes in tikv#9508, most of the code locations in the tikv source code parsing series have been changed 🧐

Yep. The source code reading series is not timely. We are planning to build a dev guide including understanding TiKV and keep it up-to-date, as [how rustc dev guide did](https://rustc-dev-guide.rust-lang.org/).

You can join [the discussion on our developer forum](https://internals.tidb.io/t/topic/46) and share you ideas. Note that we might focus on TiDB sql layer first, but TiKV is in consideration.

**Comment by tisonkun** [comment]
Thanks for your contribution!

**Pull request merged**
